project_id = "zdtyaxvfcfllrwgeoivs"

[functions.admin-reset-credentials]
verify_jwt = true

[functions.confirm-password-reset]
verify_jwt = false

[functions.ai-alert-analyzer]
verify_jwt = false

[functions.cungacash-ai]
verify_jwt = true
